#!/bin/bash

# To obtain fresh list
# apm list --installed --bare | sed 's/@.*$//' | sed 's/^/aix /'
#

##############################################################################

easy_install scspell

function bci() {
  pkg="$1"
  if ! brew cask list -1 | grep -q "^${pkg}\$"; then
    brew cask install "$@"
  fi
}

function aix() {
  pkg="$1"
  if ! apm ls -b -i | sed 's/@.*$//' | grep -q "^${pkg}\$"; then
    apm install "$@"
  fi
}

aix Sublime-Style-Column-Selection
aix atom-beautify
aix block-comment-lines
aix change-case
aix file-icons
aix find-selection
aix git-plus
aix haskell-grammar
aix hex
aix highlight-selected
aix jumpy
aix language-babel
aix language-dotfiles
aix language-ini
aix language-ocaml
aix language-thrift
aix lines
aix local-history
aix merge-conflicts
aix navigation-history
aix nuclide
aix preview-plus
aix project-manager
aix sort-lines
aix symbols-tree-view
aix tab-close-shift-click
aix text-pastry
aix tool-bar

unset -f aix
unset -f bci
