#!/bin/bash

# To obtain fresh list
# apm list --installed --bare | sed 's/@.*$//' | sed 's/^/aix /'
#

##############################################################################

easy_install scspell

function bci() {
  pkg="$1"
  if ! brew cask list -1 | grep -q "^${pkg}\$"; then
    brew cask install "$@"
  fi
}

function aix() {
  pkg="$1"
  if ! apm ls -b -i | sed 's/@.*$//' | grep -q "^${pkg}\$"; then
    apm install "$@"
  fi
}

aix Sublime-Style-Column-Selection
aix atom-beautify
aix block-comment-lines
aix change-case
aix color-picker
aix file-icons
aix find-selection
aix git-plus
aix haskell-grammar
aix hex
aix highlight-selected
aix jumpy
aix language-babel
aix language-dotfiles
aix language-ini
aix language-ocaml
aix language-thrift
aix lines
aix linter
aix linter-eslint
aix local-history
aix merge-conflicts
aix navigation-history
aix nuclide
aix pigments
aix project-manager
aix react
aix solarized-light-js-syntax
aix solarized-one-light-ui
aix sort-lines
aix symbols-plus
aix tab-close-shift-click
aix terminal-plus
aix text-pastry
aix tool-bar

unset -f aix
unset -f bci
