#!/bin/bash

# To obtain fresh list
# apm list --installed --bare | sed 's/@.*$//'
#

##############################################################################

function bci() {
  pkg="$1"
  if ! brew cask list -1 | grep -q "^${pkg}\$"; then
    brew cask install "$@"
  fi
}

function aix() {
  pkg="$1"
  if ! apm ls -b -i | sed 's/@.*$//' | grep -q "^${pkg}\$"; then
    apm install "$@"
  fi
}

aix Sublime-Style-Column-Selection
aix atom-alignment
aix atom-beautify
aix auto-detect-indentation
aix block-comment-lines
aix change-case
aix chary-tree-view
aix chocula-syntax
aix close-on-left
aix color-picker
aix default-language
aix delete-lines
aix docblockr
aix dracula-theme
aix editorconfig
aix file-icons
aix find-selection
aix git-blame
aix git-plus
aix git-time-machine
aix hex
aix highlight-selected
aix js-autoimport
aix js-refactor
aix jscs-fixer
aix jsonlint
aix jumpy
aix language-awk
aix language-dots
aix language-ini
aix language-js-specs
aix language-swift
aix language-tmux
aix last-cursor-position
aix lines
aix linter
aix linter-csslint
aix linter-htmlhint
aix linter-javac
aix linter-jshint
aix linter-markdownlint
aix linter-package-json-validator
aix linter-scspell
aix local-history
aix merge-conflicts
aix minimap
aix native-ui
aix navigation-history
aix open-recent
aix package-list
aix pigments
aix project-manager
aix react
aix react-es6-snippets
aix refactor
aix save-session
aix set-syntax
aix sort-lines
aix source-preview-react
aix symbols-tree-view
aix tab-close-shift-click
aix text-pastry
aix todo-show
aix tree-view-copy-relative-path
aix tree-view-git-branch
aix tree-view-git-status


unset -f aix
unset -f bci
